# Install pre-commit hooks via
# pre-commit install

exclude: >
    (?x)^(
      \.vscode/settings\.json|
      tests/commonmark/commonmark\.json|
      .*\.xml|
      tests/.*\.txt
    )$

repos:

  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
    - id: isort

  - repo: https://github.com/psf/black
    rev: 21.6b0
    hooks:
    - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear==21.3.1, flake8-docstrings==1.6.0]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    - id: mypy
      args: ["--install-types", "--non-interactive"]
      additional_dependencies: ["sphinx>=3,<4", "docutils>=0.14,<0.16"]
