name: continuous-integration

on:
  push:
    branches: [main]
    tags:
      - 'v*'
  pull_request:
    branches: [main]

jobs:
  pre-commit:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - uses: pre-commit/action@v2.0.0

  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        # We need my branch of MyST-NB for compatibility
        python -m pip install https://github.com/bryanwweber/MyST-NB/archive/refs/heads/fix_cell_output_renderer.zip
        python -m pip install -e .[testing]

    - name: Run pytest
      run: pytest --cov=myst_nb_bokeh --cov-report=xml --cov-report=term-missing

  publish:
    name: Publish to PyPi
    needs: [pre-commit, tests]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build package
        run: |
          python -m pip install -U pip setuptools wheel build
          python -m build
      - name: Publish
        if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@v1.1.0
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}
